server:
  port: 8080

spring:
  application:
    name: user-service

  datasource:
  
   url: jdbc:mysql://localhost:3306/hotel_user_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
   username: root
   password: Rohit@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # Email config for forgot password
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_gmail@gmail.com      # ← your Gmail
    password: your_app_password         # ← Gmail App Password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Secret Key
jwt:
  secret: "hotel_booking_super_secret_key_2024_very_long_string"
  expiration: 86400000    # 24 hours in milliseconds

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
